### ISSUE TITLE
Code of Conduct does not list an email address in the Enforcement section

### ISSUE THREAD

**Issue by noelleleigh** [davetron5000/brutalist-web-design#12]
The sentence in question:

> Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting the project team at [INSERT EMAIL ADDRESS].

<https://github.com/davetron5000/brutalist-web-design/blob/master/CODE_OF_CONDUCT.md#enforcement>

**Comment by davetron5000** [comment]
D'oh.  Fixed now.  Thanks for noticing!
