### ISSUE TITLE
Example ad doesn't seem to follow Brutalist Web Design

### ISSUE THREAD

**Issue by Architector4** [davetron5000/brutalist-web-design#16]
The website mentions keeping elements true to its purpose - that "a link promises more information for the visitor, a button agrees to submit the visitor's information to the server".

However, later on, it features a "PROMOTION", with a button that doesn't submit the visitor's information to the server, but gives more information.

Moreso, it breaks web browsers's functionality: it's not clickable with middle mouse button to open in a new tab, and it doesn't count as a link to the web browser according to the right mouse button's context menu. As a result, a user who wants to open it in a new tab to digest the other website's content needs to separately make a new tab one way or another. That most definitely doesn't sound anything like what Brutalist Web Design is all about.

Is this intentional?

**Comment by davetron5000** [comment]
You are correct!  The original version actually did submit a form that added a copy of another book to a shopping cart, thus complying with the underlying principle.  Looks like when I changed it to promote a different book it became a link to the book's website and not a button to directly add to cart. Will fix this.  Thanks for pointing it out!

**Comment by davetron5000** [comment]
Updated so that it does submit info to a server and adds the book to the shopping cart (plus a link to learn more).
