### ISSUE TITLE
Mistaken brutalism for functionalism

### ISSUE THREAD

**Issue by repli2dev** [davetron5000/brutalist-web-design#5]
The name `brutalism` is probably mistaken for `functionalism`, maybe you were taken by the `raw`-thing which pairs nicely with raw styling.

However this architecture style is using raw materials only as a method for making very rememberable impression, outlining the construction structure and clean expression of material (not content or message). This goes against the vision outlined in the document.

To put it differently (a bit generalised):
- Brutalism: designing according to material of the <something>
- Functionalism: designing according to function of the <something>

----

On personal side, the "brutalism" has so bad meaning around (Czech Republic) here, that I firstly just ignored that as something that I do not really want. Why? The builings I came across were mostly in-human in Kafka's view descibred in America or Process.

**Comment by davetron5000** [comment]
I appreciate the info. I'm not an expert in architecture, but I stand by my interpretation, though I would only stand by it as my personal interpretation. Not meant to tell others how to do it.
